#!/bin/bash

sleep 4800
condor_submit SubmitFiles/submit_Seed41.txt
sleep 480
condor_submit SubmitFiles/submit_Seed42.txt
sleep 480
condor_submit SubmitFiles/submit_Seed43.txt
sleep 480
condor_submit SubmitFiles/submit_Seed44.txt
sleep 480
condor_submit SubmitFiles/submit_Seed45.txt
sleep 480
condor_submit SubmitFiles/submit_Seed46.txt
sleep 480
condor_submit SubmitFiles/submit_Seed47.txt
sleep 480
condor_submit SubmitFiles/submit_Seed48.txt
sleep 480
condor_submit SubmitFiles/submit_Seed49.txt
sleep 480
condor_submit SubmitFiles/submit_Seed50.txt
sleep 480
condor_submit SubmitFiles/submit_Seed51.txt
sleep 480
condor_submit SubmitFiles/submit_Seed52.txt
sleep 480
condor_submit SubmitFiles/submit_Seed53.txt
sleep 480
condor_submit SubmitFiles/submit_Seed54.txt
sleep 480
condor_submit SubmitFiles/submit_Seed55.txt
sleep 480
condor_submit SubmitFiles/submit_Seed56.txt
sleep 480
condor_submit SubmitFiles/submit_Seed57.txt
sleep 480
condor_submit SubmitFiles/submit_Seed58.txt
sleep 480
condor_submit SubmitFiles/submit_Seed59.txt
sleep 480
condor_submit SubmitFiles/submit_Seed60.txt

sleep 
condor_submit SubmitFiles/submit_Seed61.txt
sleep 480
condor_submit SubmitFiles/submit_Seed62.txt
sleep 480
condor_submit SubmitFiles/submit_Seed63.txt
sleep 480
condor_submit SubmitFiles/submit_Seed64.txt
sleep 480
condor_submit SubmitFiles/submit_Seed65.txt
sleep 480
condor_submit SubmitFiles/submit_Seed66.txt
sleep 480
condor_submit SubmitFiles/submit_Seed67.txt
sleep 480
condor_submit SubmitFiles/submit_Seed68.txt
sleep 480
condor_submit SubmitFiles/submit_Seed69.txt
sleep 480
condor_submit SubmitFiles/submit_Seed70.txt
sleep 480
condor_submit SubmitFiles/submit_Seed71.txt
sleep 480
condor_submit SubmitFiles/submit_Seed72.txt
sleep 480
condor_submit SubmitFiles/submit_Seed73.txt
sleep 480
condor_submit SubmitFiles/submit_Seed74.txt
sleep 480
condor_submit SubmitFiles/submit_Seed75.txt
sleep 480
condor_submit SubmitFiles/submit_Seed76.txt
sleep 480
condor_submit SubmitFiles/submit_Seed77.txt
sleep 480
condor_submit SubmitFiles/submit_Seed78.txt
sleep 480
condor_submit SubmitFiles/submit_Seed79.txt
sleep 480
condor_submit SubmitFiles/submit_Seed80.txt

sleep 
condor_submit SubmitFiles/submit_Seed81.txt
sleep 480
condor_submit SubmitFiles/submit_Seed82.txt
sleep 480
condor_submit SubmitFiles/submit_Seed83.txt
sleep 480
condor_submit SubmitFiles/submit_Seed84.txt
sleep 480
condor_submit SubmitFiles/submit_Seed85.txt
sleep 480
condor_submit SubmitFiles/submit_Seed86.txt
sleep 480
condor_submit SubmitFiles/submit_Seed87.txt
sleep 480
condor_submit SubmitFiles/submit_Seed88.txt
sleep 480
condor_submit SubmitFiles/submit_Seed89.txt
sleep 480
condor_submit SubmitFiles/submit_Seed90.txt
sleep 480
condor_submit SubmitFiles/submit_Seed91.txt
sleep 480
condor_submit SubmitFiles/submit_Seed92.txt
sleep 480
condor_submit SubmitFiles/submit_Seed93.txt
sleep 480
condor_submit SubmitFiles/submit_Seed94.txt
sleep 480
condor_submit SubmitFiles/submit_Seed95.txt
sleep 480
condor_submit SubmitFiles/submit_Seed96.txt
sleep 480
condor_submit SubmitFiles/submit_Seed97.txt
sleep 480
condor_submit SubmitFiles/submit_Seed98.txt
sleep 480
condor_submit SubmitFiles/submit_Seed99.txt
sleep 480
condor_submit SubmitFiles/submit_Seed100.txt

